server:
  port: 5081
  contextPath: /
spring:
  datasource:
    url: jdbc:hsqldb:file:database\\kataDB
    username: SA
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.security: INFO
